### ISSUE TITLE
Generate quality prompts for images

### ISSUE THREAD

**Issue by YaoShunyu19** [Q-Future/Q-Ground#3]
Thanks for your meaningful work. I would like to know which Co-Instruct model was used to generate the quality prompts for the images, as mentioned in Section A2 (GPT-4V Annotation) on page 11 of the paper. Additionally, I would appreciate your recommendation on which Co-Instruct model to use.
Thanks!

**Comment by chaofengc** [comment]
Please refer to the github repo: https://github.com/Q-Future/Co-Instruct
